# docker-compose.yml
version: "3.8"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ./.env
    restart: always
