primary_agent:
  llm: gemini-1.5-flash # More token efficient than gemini-2.0
  llm_temperature: 0.0

rag_configs:
  unstructured_docs: "data/unstructured_docs/swiss_airline_policy"
  vectordb: "data/airline_policy_vectordb"
  collection_name: documnets.rag
  llm: gemini-1.5-flash # More cost effective for RAG
  llm_temperature: 0.9
  embedding_model: models/embedding-001
  chunk_size: 1000
  chunk_overlap: 200
  k: 2

sqlagent_configs:
  sqldb_dir: "data/Chinook.db"
  llm: "gemini-1.5-flash" # Much more token efficient for SQL generation
  llm_temperature: 0.0

langsmith:
  tracing: "true"
  project_name: "rag_sqlagent_project"

memory:
  directory: memory

tavily_search_api:
  tavily_search_max_results: 2

graph_configs:
  thread_id: 1 # This can be adjusted to assign a unique value for each user session, so it's easier to access data later on.
