# ICONNET Application Secrets Configuration
# Copy this file to .streamlit/secrets.toml and fill in your actual values
#
# IMPORTANT: Never commit secrets.toml to version control!
# Add .streamlit/secrets.toml to your .gitignore file

[database]
# PostgreSQL Database Configuration
DB_HOST = ""
DB_NAME = ""
DB_USER = ""
DB_PASSWORD = ""
DB_PORT = ""

[supabase]
# Supabase Configuration (if using Supabase)
url = ""
service_role_key = ""

[firebase]
# Firebase Configuration
firebase_key_json = """
{
  "type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "",
  "token_uri": "",
  "auth_provider_x509_cert_url": "",
  "client_x509_cert_url": "",
  "universe_domain": ""
}
"""

# This firebase_api is at the root level, consistent with your secrets.toml
firebase_api = ""

# SMTP Configuration
[smtp]
server = ""
port = ""
username = ""
password = ""

# Gemini Configuration
[gemini]
api_key = ""

# Langsmith Configuration
[langsmith]
api_key = ""

# Tavily Configuration
[tavily]
api_key = ""

# Airflow Configuration
[airflow]
base_url = ""
username = ""
password = ""

# Instructions:
# 1. Copy this file to .streamlit/secrets.toml
# 2. Replace all placeholder values with your actual configuration
# 3. Make sure .streamlit/secrets.toml is in your .gitignore
# 4. For local development, you can leave some sections empty to run in demo mode